apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tester
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-demo-generator
      labels:
        app: kafka-demo-generator
    spec:
      containers:
      - name: demo-consumer
        image: markfjohnson/python-kafka-k8s
        command: ["/usr/local/bin/python"]
        imagePullPolicy: Always
        args: ["-V"]