apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flink-demo-generator
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-demo-generator
      labels:
        app: kafka-demo-generator
    spec:
      containers:
      - name: demo-consumer
        image: markfjohnson/python-kafka-k8s
        command: ["python kafka_consumer.py"]
        imagePullPolicy: Always
        args: ["--broker", "broker.kafka.l4lb.thisdcos.directory:9092"]